//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using WorkShop.DAL;

//#nullable disable

//namespace WorkShop.DAL.Migrations
//{
//    [DbContext(typeof(WorkShopDbContext))]
//    [Migration("20250316005158_initial")]
//    partial class initial
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.3")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("WorkShop.DAL.Models.Employee", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("CreateAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Department")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<decimal>("Salary")
//                        .HasColumnType("decimal(18,2)");

//                    b.HasKey("Id");

//                    b.HasIndex("Email")
//                        .IsUnique();

//                    b.ToTable("Employees");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
